# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string
    secrets:
      IONOS_API_KEY:
        required: true
      STRIPE_SECRET_KEY:
        required: true
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
        required: true

env:
  DEPLOYMENT_FOLDER: out

jobs:
# Please do not rename this job
  build-project:
    name: build LASERovici
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        run: |
          npm install
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }} npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 1d4290bb-1634-4dd1-9de6-8a5e55b910ba
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/LASERovici/config.yaml
          action: upload
